account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('', views.index, name='profile'),
    path('register/', views.register, name='register'),
    path('signin/', views.signin, name='signin')
]

home/urls.py
from django.urls import path
from .import views


app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
]

lamad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django_countries.fields import CountryField
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.conf import settings

# Create your models here.


class CustomUser(AbstractUser):
    username = models.CharField(
        _("username"),
        max_length=20,
        unique=True,
        help_text=_("Required.20 characters or fewer.\
                Letters and digits only."),
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    
    email = models.CharField(
        _("email address"),
        max_length=30,
        unique=True,
        error_messages={
            "unique": _("A user with that email address already exists."),
        },
    )

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = f'{self.first_name} {self.last_name}'
        return full_name

    def __str__(self):
        return self.username

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Profile(models.Model):
    """User profile to extend the account profile
    Added images so they can be displayed on the blog if users comment.
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    street_address1 = models.CharField(blank=True, max_length=100)
    street_address2 = models.CharField(blank=True, default=00, max_length=100)
    town_or_city = models.CharField(blank=True, max_length=30)
    county = models.CharField(blank=True, default=00, max_length=30)
    postcode = models.CharField(blank=True, max_length=30)
    country = CountryField(blank=True, max_length=30)
    avatar = models.ImageField(blank=True, upload_to='userprofile')

    def image_tag(self):
        if self.avatar:
            return mark_safe(
                '<img src="%s" height="50" width="50">' % self.avatar.url
                )
        return "No image found"

    def __str__(self):
        return self.user.username

    def full_address(self):
        return f'(self.street_address1) (self.street_address2)'

account/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    '''
        this view renders the profile page of a logged in user
    '''
    template_name = 'account/profile.html'
    return render(request, template_name)


def register(request):
    '''
        this view shows the registration form and enables user to 
        register an account
    '''
    template_name = 'account/register.html'
    return render(request, template_name)


def signin(request):
    '''
        this view shows the login form and enables
        a registered user to login the system
    '''
    template_name = 'account/login.html'
    return render(request, template_name)

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    context = {}
    template_name = 'home/home.html'
    return render(request, template_name, context)

home/templates/home/home.html
{% extends 'base.html' %}

{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<!-- slider goes here -->
<div class="row">
<div class="container-fluid">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'images/huhclasse10_3.webp' %}" alt="First slide">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="row row-overlay">
                    <div class="col-12 overlay-message">
                        <div class="overlay">
                            <h1 class="cta-h1">Welcome to Lamad</h1>
                            <h2 class="cta-h2">Sewing Machine Shop With a Difference</h2>
                            <a class="btn shop-now-button m-0" href="{% url 'home:home' %}">Shop Now</a>
                        </div>
                    </div>
                </div>
               
                
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/jamc9450qcp_4.webp' %}" alt="Second slide">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="row row-overlay">
                    <div class="col-12 overlay-message">
                        <div class="overlay">
                            <h1 class="cta-h1">Welcome to Lamad</h1>
                            <h2 class="cta-h2">Sewing Machine Shop With a Difference</h2>
                            <a class="btn shop-now-button m-0" href="{% url 'home:home' %}">Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/mc945qdc.webp' %}" alt="professional Janome sewing machine ">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="row row-overlay">
                    <div class="col-12 overlay-message">
                        <div class="overlay">
                            <h1 class="cta-h1">Welcome to Lamad</h1>
                            <h2 class="cta-h2">Sewing Machine Shop With a Difference</h2>
                            <a class="btn shop-now-button m-0" href="{% url 'home:home' %}">Shop Now</a>
                        </div>
                    </div>
                </div>
                
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</div>
</div>
<!-- end of slider -->
<!--Dividing section & features-->
    <!--Heading-->
    <div class="row">
    <div class="container-fluid features-cont">
        <div class="row">
            <div class="col-sm-12 mt-5">
                <h3 class="text-center text-sly what-heading">What we do</h3>
            </div>
        </div>
        <!--First col-->
        <div class="row div-row">
            <div class="col-sm-12 col-md-4 div-col">
                <i class="fa-solid fa-gift feat-icon"></i>
                <p>Provide you with excellent hand made grooming products to keep you looking <strong>Razor Sharp</strong></p>
            </div>
            <!--Second col-->
            <div class="col-sm-12 col-md-4 div-col">
                <i class="fa-solid fa-truck-fast feat-icon"></i>
                <p>Ship <strong>lightening fast</strong> to get your products out to you before you know it.</p>
            </div>
            <!--Third col-->
            <div class="col-sm-12 col-md-4 div-col">
                <i class="fa-solid fa-repeat feat-icon"></i>
                <p>Provide you with <strong>Expert</strong> & Professional insight on tips, tricks and <strong>technique</strong> so you always look your best self.</p>
            </div>
        </div>
    </div>
    </div>
<!-- content goes here -->
<div class="row mt-5 mb-5">
 <h1>home page</h1>
 <h2>home page</h2>
 <h3>home page</h3>
 <h4>home page</h4>
 <h5>home page</h5>
 <h6>home page</h6>
</div>
 <!-- endof content -->
{% endblock %}

templates/includes/main-nav.html
{% load  static %}
<div class="collapse navbar-collapse nav-bg-color" id="main-nav">
    <a href="{% url 'home:home' %}" class="navbar-brand" id="small_screen">
        <img src="{% static 'images/logo-no-background.webp' %}" alt="logo image" width="180" class="img-fluid">
      </a>
    <ul class="navbar-nav w-auto mx-auto">
        <li class="nav-item">
            <a class="logo-font font-weight-bold nav-link text-sly mr-5" href="{% url 'home:home' %}" id="home-link">
                Home
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-sly mr-5" href="#" id="products-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Products
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="contact-link">
                <!-- {% for category in menu %}
                    <a href="{{ category.get_url }}" class="dropdown-item">{{category.name}}</a>
                {% endfor %}
                <a href="#" class="dropdown-item">All Products</a> -->
            </div>
        </li>
        <li class="nav-item">
            <a class="logo-font font-weight-bold nav-link text-sly mr-5" href="#" id="subscriptions-link">
                Blog
            </a>
        </li>
        <li>
            <a class="logo-font font-weight-bold nav-link text-sly mr-5" href="#" id="wish-link">
                Wishlist
            </a> 
        </li>
        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-sly" href="#" id="contact-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Contact
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="contact-link">
                <a href="#" class="dropdown-item">Contact</a>
                <a href="#" class="dropdown-item">Shipping & Delivery</a>
                <a href="#" class="dropdown-item">FAQ's</a>
                <a href="#" class="dropdown-item">Returns</a>
            </div>
        </li>
    </ul>
</div>

templates/includes/mobile-top-header.html
<ul class="list-inline list-unstyled text-center text-lg-right my-0">
    <li class="list-inline-item">
        <a class="text-sly nav-link d-block d-lg-none" href="#" id="mobile-search" aria-label="Search our website" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="text-center mobile-responsive">
                <div><i class="fas fa-search fa-lg text-sly"></i></div>
                <p class="my-0 text-sly">Search</p>
            </div>
        </a>
        <div class="dropdown-menu border-0 w-100 p-3 rounded-0 my-0" aria-labelledby="mobile-search">
            <form class="form" method="GET" action="#">
                <div class="input-group w-100">
                    <input class="form-control border border-black rounded-0" type="text" name="q" placeholder="Search our site">
                    <div class="input-group-append">
                        <button class="form-control form-control btn nav-bg-color border border-black rounded-0" type="submit">
                            <span class="icon">
                                <i class="fas fa-search"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </li>
    <li class="list-inline-item dropdown">
        <a class="text-black nav-link d-block d-lg-none" href="#" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="text-center mobile-responsive">
                {% if request.user.is_authenticated %}
                    <div><i class="fas fa-user fa-lg"></i></div>
                    <p class="my-0 text-sly">My Account</p>
                {% else %}
                    <div><i class="fas fa-user fa-lg"></i></div>
                    <p class="my-0 text-sly">Login / Sign Up</p>
                {% endif %}
            </div>
        </a>
        <div class="dropdown-menu border-0" aria-labelledby="user-options">
            {% if request.user.is_authenticated %}
                {% if request.user.is_superadmin %}
                    <a href="#" class="dropdown-item">Product Management</a>
                {% endif %}
                <a href="#" class="dropdown-item">My Profile</a>
                <a href="#" class="dropdown-item">Logout</a>
            {% else %}
                <a href="#" class="dropdown-item">Register</a>
                <a href="#" class="dropdown-item">Login</a>
            {% endif %}
        </div>
    </li>
    <li class="list-inline-item">
        <a class="{% if grand_total %}text-primary font-weight-bold{% else %}text-black{% endif %} nav-link d-block d-lg-none" href="#">
            <div class="text-center mobile-responsive">
                <div><i class="fas fa-cart-shopping fa-lg"></i></div>
                <p class="my-0 text-sly">
                    {% if grand_total %}
                        ${{ grand_total|floatformat:2 }}
                    {% else %}
                        $0.00
                    {% endif %}
                </p>
            </div>
        </a>
    </li>
</ul>

templates/includes/toasts/toast_error.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-danger"></div>
    <div class="w-100 toast-capper bg-danger"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Error!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}        
    </div>
</div>

templates/includes/toasts/toast_info.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-info"></div>
    <div class="w-100 toast-capper bg-info"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Alert!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}        
    </div>
</div>

templates/includes/toasts/toast_success.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-success"></div>
    <div class="w-100 toast-capper bg-success"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Success!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}        
    </div>
</div>

templates/includes/toasts/toast_warning.html
<div class="toast custom-toast rounded-0 border-top-0" data-autohide="false">
    <div class="arrow-up arrow-warning"></div>
    <div class="w-100 toast-capper bg-warning"></div>
    <div class="toast-header bg-white text-dark">
        <strong class="mr-auto">Warning!</strong>
        <button type="button" class="ml-2 mb-1 close text-dark" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body bg-white">
        {{ message }}        
    </div>
</div>